<a href="https://colab.research.google.com/github/kvraagul/Numpy_and_Pandas/blob/main/NUMPY_and_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely. NumPy stands for Numerical Python.

In [ ]:
import numpy as np

# MULTI-DIMENSIONAL ARRAY

In [ ]:
np.array([2,3])

array([2, 3])

In [ ]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# ZEROS

In [ ]:
np.zeros((1,2))

array([[0., 0.]])

In [ ]:
np.zeros((6,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# FULL

In [ ]:
np.full((2,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
np.full((1,3),8)

array([[8, 8, 8]])

# ARANGE

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# RANDOM

Initialize numpy arrays with random numbers

In [ ]:
np.random.randint(1,10,5)

In [ ]:
np.random.randint(1,5,10)

# SHAPE

Checking the shape of numpy arrays

In [ ]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n1.shape

(2, 4)

In [ ]:
n1.shape=(4,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
n2=np.array([1,2])
n2.shape

(2,)

# JOINING NUMPY ARRAYS

stack() function is used to join a sequence of same dimension arrays along a new axis.

In [ ]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

In [ ]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

# INTERSECTION AND DIFFERENCES

INTERSECT - Find similar numbers in numpy arrays

In [ ]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([40,50,60,70,80,90])
np.intersect1d(n1,n2)

array([40, 50, 60])

DIFFERENCE - Difference w.r.t n1

In [ ]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([40,50,60,70,80,90])
np.setdiff1d(n1,n2)

array([10, 20, 30])

DIFFERENCE - Difference w.r.t n2

In [ ]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([40,50,60,70,80,90])
np.setdiff1d(n2,n1)

array([70, 80, 90])

# NUMPY ARRAY MATHEMATICS

ADDITION

In [ ]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.sum([n1,n2])

210

In [ ]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.sum([n1,n2],axis=0)

#axis=0 (for remember purpose: vertical,rows)

array([50, 70, 90])

In [ ]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.sum([n1,n2],axis=1)

#axis=1 (for remember purpose: horizontal,columns)

array([ 60, 150])

BASIC ADD SUB MUL DIV

In [ ]:
n1=np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [ ]:
n1=n1*5
n1

array([ 55, 105, 155])

In [ ]:
n1=n1-10
n1

array([ 45,  95, 145])

In [ ]:
n1=n1*10
n1

array([ 450,  950, 1450])

MEAN , MEDIAN , STANDARD DEVIATION

In [ ]:
n1=np.array([10,20,30])
np.mean(n1)


20.0

In [ ]:
n1=np.array([10,20,30,40,450])
np.median(n1)

30.0

In [ ]:
np.std(n1)

170.29386365926402

# SAVE AND LOAD NUMPY ARRAY

In [ ]:
num1=np.array([10,20,30,40,50])
np.save('my_numpy',num1)

In [ ]:
num2=np.load('my_numpy.npy')
num2

array([10, 20, 30, 40, 50])

# PANDAS

PANDAS stands for PANel DAta and it is the core library for Data Maniplulation and Data Analysis. It consists of single and multi-dimensinal data structures for Data Manipulations.

Single Dimensional - Series Object

Multi Dimensional  - Data Frame

In [ ]:
import pandas as pd

# PANDAS SERIES OBJECT


# Series object is one dimensional labeled array

In [ ]:
s1=pd.Series([1,2,3,4,5,6])
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
s1=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])
s1

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [ ]:
s2={'a':10,'b':20,'c':30}
pd.Series(s2,index=['b','c','a','d'])

b    20.0
c    30.0
a    10.0
d     NaN
dtype: float64

# EXTRACTING ELEMENTS

In [ ]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
print(s1[5])
print(s1[7])

6
8


In [ ]:
s1[:-1]

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [ ]:
s1[:4]

0    1
1    2
2    3
3    4
dtype: int64

# SIMPLE MATHS

In [ ]:
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
s1+1

0     2
1     3
2     4
3     5
4     6
5     7
6     8
7     9
8    10
9    11
dtype: int64

In [ ]:
s1*10

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [ ]:
s1-1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [ ]:
s2=pd.Series([12,11,19,10,12,1,2,3,4,5])
s1+s2

0    13
1    13
2    22
3    14
4    17
5     7
6     9
7    11
8    13
9    15
dtype: int64


# Data Frame is a 2 dimensional labelled data structure



data frame comprises of rows and columns

In [ ]:

pd.DataFrame({'Name':['MR.X','MR.Y','MR.Z'],'marks':[80,90,70]})

Name  marks
0  MR.X     80
1  MR.Y     90
2  MR.Z     70

In [ ]:
pd.read_csv('enter a file name')

In [ ]:
pd.head()

In [ ]:
pd.tail()